// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands.LauncherCommands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj2.command.Subsystem;
import frc.robot.subsystems.launcher;
import edu.wpi.first.wpilibj2.command.SubsystemBase;


/**
 *
 */

public class LauncherFollowTune extends CommandBase {
    private launcher launcher;
    //private double value;

    public LauncherFollowTune(launcher subsystem) {
    
        launcher = subsystem;
        //double value = 0;
        addRequirements(launcher);  
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        System.out.println("Launcher Tune Initialized");
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
       launcher.launcherFollowTune();
    }

    
    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        
        return false;

    }
}
