

package frc.robot.commands.LauncherCommands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj2.command.Subsystem;
import frc.robot.subsystems.launcher;


/**
 *
 */

public class LauncherStop extends CommandBase {
    private launcher launcher;

  

    public LauncherStop(launcher subsystem) {
    
        Subsystem launcher = subsystem;
        addRequirements(launcher);

       
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        System.out.println("Stop!");
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        launcher.launcherLeadPercentPower(0);
        launcher.launcherFollowPercentPower(0);
    }

 

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return true;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
